spring:
  application:
    name: eureka-client
server:
  port: 8081
eureka:
  client:
    service-url.defaultZone: http://justk:kong@localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
