server:
  port: 1996
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.139.244:3306/website-kong?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: "@JustKong."
  redis:
    host: 127.0.0.1
    port: 6379
    password: kong
  rabbitmq:
    dynamic: true
    host: 106.12.139.244
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
        acknowledge-mode: auto
    publisher-confirms: true
    publisher-returns: true
  dubbo:
    application:
      name: web-server
    registry:
      address: 106.12.139.244
      port: 2191
    protocol:
      name: dubbo
      port: 20080
    scan: com.biosh.owner.web.controller
mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rabbitmq:
  exchange:
    login: login-exchange
  queue:
    login: login-queue
