spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.139.244:3306/website-kong?useSSL=false&serverTimeZone=GMT%2B8
    username: root
    password: "@JustKong."
  redis:
    host: 106.12.139.244
    password: "@JustKong."
    port: 6379
  dubbo:
    application:
      name: mp-server
    registry:
      address: 106.12.139.244
      port: 2181
      protocol: zookeeper
    protocol:
      name: dubbo
      port: 20080
    scan: com.biosh.owner.mp.service

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:mappers/*.xml
