spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.139.244:3306/website-kong?useSSL=false&serverTimeZone=GMT%2B8
    username: root
    password: "@JustKong."
  redis:
    host: 106.12.139.244
    password: "@JustKong."
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
